package cmn

import "github.com/ethereum/go-ethereum/common"

var PredefinedBlockchains []Blockchain = []Blockchain{
	{
		Name:          "Ethereum",
		Url:           "https://ethereum-rpc.publicnode.com",
		ChainID:       1,
		ExplorerUrl:   "https://etherscan.io",
		WTokenAddress: common.HexToAddress("0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
		Currency:      "ETH",
	},
	{
		Name:          "PulseChain",
		Url:           "wss://rpc.pulsechain.com",
		ChainID:       369,
		ExplorerUrl:   "https://scan.9inch.io/#/",
		Currency:      "PLS",
		WTokenAddress: common.HexToAddress("0xA1077a294dDE1B09bB078844df40758a5D0f9a27"),
	},
	{
		Name:        "PulseChain Testnet v4",
		Url:         "https://rpc.v4.testnet.pulsechain.com",
		ChainID:     943,
		ExplorerUrl: "https://scan.v4.testnet.pulsechain.com/#/",
		Currency:    "tPLS",
	},
	{
		Name:        "Avalanche C-Chain",
		Url:         "https://api.avax.network/ext/bc/C/rpc",
		ChainID:     43114,
		ExplorerUrl: "https://snowtrace.io",
		Currency:    "AVAX",
	},
	{
		Name:          "Binance Smart Chain Mainnet",
		Url:           "https://bsc-dataseed1.binance.org",
		ChainID:       56,
		ExplorerUrl:   "https://bscscan.com",
		Currency:      "BNB",
		WTokenAddress: common.HexToAddress("0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c"),
	},
	{
		Name:        "Base",
		Url:         "https://mainnet.base.org",
		ChainID:     8453,
		ExplorerUrl: "",
		Currency:    "ETH",
	}, {
		Name:        "Fantom Opera",
		Url:         "https://rpc.ftm.tools",
		ChainID:     250,
		ExplorerUrl: "https://ftmscan.com",
		Currency:    "FTM",
	},
	{
		Name:        "Polygon Mainnet",
		Url:         "https://polygon-rpc.com/",
		ChainID:     137,
		ExplorerUrl: "https://polygonscan.com",
		Currency:    "MATIC",
	},
	{
		Name:        "Polygon zkEVM",
		Url:         "https://polygon-zkevm.blockpi.network/v1/rpc/public",
		ChainID:     1101,
		ExplorerUrl: "https://zkevm.polygonscan.com/",
		Currency:    "ETH",
	},
	{
		Name:        "Cronos Mainnet Beta",
		Url:         "https://evm.cronos.org",
		ChainID:     25,
		ExplorerUrl: "https://cronos.org/explorer",
		Currency:    "CRO",
	},
	{
		Name:        "Arbitrum One",
		Url:         "wss://arbitrum-one.publicnode.com",
		ChainID:     42161,
		ExplorerUrl: "https://arbiscan.io,https://explorer.arbitrum.io",
		Currency:    "ETH",
	},
	{
		Name:        "Klaytn Mainnet Cypress",
		Url:         "https://public-node-api.klaytnapi.com/v1/cypress",
		ChainID:     8217,
		ExplorerUrl: "https://scope.klaytn.com",
		Currency:    "KLAY",
	},
	{
		Name:        "Harmony Mainnet Shard 0",
		Url:         "https://api.harmony.one",
		ChainID:     1666600000,
		ExplorerUrl: "https://explorer.harmony.one",
		Currency:    "ONE",
	},
	{
		Name:        "Aurora Mainnet",
		Url:         "https://mainnet.aurora.dev",
		ChainID:     1313161554,
		ExplorerUrl: "https://aurorascan.dev",
		Currency:    "ETH",
	},
	{
		Name:        "Huobi ECO Chain Mainnet",
		Url:         "https://http-mainnet.hecochain.com",
		ChainID:     128,
		ExplorerUrl: "https://hecoinfo.com",
		Currency:    "HT",
	},
	{
		Name:        "Celo Mainnet",
		Url:         "https://forno.celo.org",
		ChainID:     42220,
		ExplorerUrl: "https://explorer.celo.org",
		Currency:    "CELO",
	},
	{
		Name:        "Metis Andromeda Mainnet",
		Url:         "https://andromeda.metis.io/owner1088",
		ChainID:     1088,
		ExplorerUrl: "https://andromeda-explorer.metis.io",
		Currency:    "METIS",
	},
	{
		Name:        "Optimism",
		Url:         "https://mainnet.optimism.io/",
		ChainID:     10,
		ExplorerUrl: "https://optimistic.etherscan.io",
		Currency:    "ETH",
	},
	{
		Name:        "Gnosis Chain formerly xDai",
		Url:         "https://rpc.gnosischain.com",
		ChainID:     100,
		ExplorerUrl: "https://gnosisscan.io,https://gnosis.blockscout.com,https://gnosis.dex.guru",
		Currency:    "xDAI",
	},
	{
		Name:        "Moonriver",
		Url:         "https://rpc.api.moonriver.moonbeam.network",
		ChainID:     1285,
		ExplorerUrl: "https://moonriver.moonscan.io",
		Currency:    "MOVR",
	},
	{
		Name:        "Theta Mainnet",
		Url:         "https://eth-rpc-api.thetatoken.org/rpc",
		ChainID:     361,
		ExplorerUrl: "https://explorer.thetatoken.org",
		Currency:    "TFUEL",
	},
	{
		Name:        "Emerald Paratime Mainnet",
		Url:         "https://emerald.oasis.dev",
		ChainID:     42262,
		ExplorerUrl: "https://explorer.emerald.oasis.dev",
		Currency:    "ROSE",
	},
	{
		Name:        "Telos EVM Mainnet",
		Url:         "https://mainnet.telos.net/evm",
		ChainID:     40,
		ExplorerUrl: "https://teloscan.io",
		Currency:    "TLOS",
	},
	{
		Name:        "Fusion Mainnet",
		Url:         "https://mainnet.anyswap.exchange",
		ChainID:     32659,
		ExplorerUrl: "",
		Currency:    "FSN",
	},
	{
		Name:        "Moonbeam",
		Url:         "https://rpc.api.moonbeam.network",
		ChainID:     1284,
		ExplorerUrl: "https://moonbeam.moonscan.io",
		Currency:    "GLMR",
	},
	{
		Name:        "RSK Mainnet",
		Url:         "https://public-node.rsk.co",
		ChainID:     30,
		ExplorerUrl: "https://explorer.rsk.co",
		Currency:    "RBTC",
	},
	{
		Name:        "IoTeX Network Mainnet",
		Url:         "https://babel-api.mainnet.iotex.io",
		ChainID:     4689,
		ExplorerUrl: "https://iotexscan.io",
		Currency:    "IOTX",
	},
	{
		Name:        "OKExChain Mainnet",
		Url:         "https://exchainrpc.okex.org",
		ChainID:     66,
		ExplorerUrl: "https://www.oklink.com/okexchain",
		Currency:    "OKT",
	},
	{
		Name:        "Boba Network",
		Url:         "https://mainnet.boba.network/",
		ChainID:     288,
		ExplorerUrl: "https://blockexplorer.boba.network",
		Currency:    "ETH",
	},
	{
		Name:        "KCC Mainnet",
		Url:         "https://rpc-mainnet.kcc.network",
		ChainID:     321,
		ExplorerUrl: "https://explorer.kcc.io/en",
		Currency:    "KCS",
	},
	{
		Name:        "Wanchain",
		Url:         "https://gwan-ssl.wandevs.org:56891/",
		ChainID:     888,
		ExplorerUrl: "",
		Currency:    "WAN",
	},
	{
		Name:        "Velas EVM Mainnet",
		Url:         "https://evmexplorer.velas.com/rpc",
		ChainID:     106,
		ExplorerUrl: "https://evmexplorer.velas.com",
		Currency:    "VLX",
	},
	{
		Name:        "Smart Bitcoin Cash",
		Url:         "https://smartbch.greyh.at",
		ChainID:     10000,
		ExplorerUrl: "",
		Currency:    "BCH",
	},
	{
		Name:        "Songbird Canary-Network",
		Url:         "https://songbird.towolabs.com/rpc",
		ChainID:     19,
		ExplorerUrl: "https://songbird-explorer.flare.network",
		Currency:    "SGB",
	},
	{
		Name:        "zkSync Era Mainnet",
		Url:         "https://zksync2-mainnet.zksync.io",
		ChainID:     324,
		ExplorerUrl: "https://explorer.zksync.io",
		Currency:    "ETH",
	},
	{
		Name:        "Fuse Mainnet",
		Url:         "https://rpc.fuse.io",
		ChainID:     122,
		ExplorerUrl: "",
		Currency:    "FUSE",
	},
	{
		Name:        "Shiden",
		Url:         "https://rpc.shiden.astar.network:8545",
		ChainID:     336,
		ExplorerUrl: "https://shiden.subscan.io",
		Currency:    "SDN",
	},
	{
		Name:        "CoinEx Smart Chain Mainnet",
		Url:         "https://rpc.coinex.net",
		ChainID:     52,
		ExplorerUrl: "https://www.coinex.net",
		Currency:    "cet",
	},
	{
		Name:        "Callisto Mainnet",
		Url:         "https://clo-geth.0xinfra.com",
		ChainID:     820,
		ExplorerUrl: "",
		Currency:    "CLO",
	},
	{
		Name:        "ThunderCore Mainnet",
		Url:         "https://mainnet-rpc.thundercore.com",
		ChainID:     108,
		ExplorerUrl: "https://scan.thundercore.com",
		Currency:    "TT",
	},
	{
		Name:        "Elastos Smart Chain",
		Url:         "https://api.elastos.io/eth",
		ChainID:     20,
		ExplorerUrl: "https://eth.elastos.io",
		Currency:    "ELA",
	},
	{
		Name:        "Meter Mainnet",
		Url:         "https://rpc.meter.io",
		ChainID:     82,
		ExplorerUrl: "https://scan.meter.io",
		Currency:    "MTR",
	},
	{
		Name:        "TomoChain",
		Url:         "https://rpc.tomochain.com",
		ChainID:     88,
		ExplorerUrl: "",
		Currency:    "TOMO",
	},
	{
		Name:        "Energy Web Chain",
		Url:         "https://rpc.energyweb.org",
		ChainID:     246,
		ExplorerUrl: "https://explorer.energyweb.org",
		Currency:    "EWT",
	},
	{
		Name:        "Syscoin Mainnet",
		Url:         "https://rpc.syscoin.org",
		ChainID:     57,
		ExplorerUrl: "https://explorer.syscoin.org",
		Currency:    "SYS",
	},
	{
		Name:        "Ubiq",
		Url:         "https://rpc.octano.dev",
		ChainID:     8,
		ExplorerUrl: "https://ubiqscan.io",
		Currency:    "UBQ",
	},
	{
		Name:        "Polis Mainnet",
		Url:         "https://rpc.polis.tech",
		ChainID:     333999,
		ExplorerUrl: "",
		Currency:    "POLIS",
	},
	{
		Name:        "Zyx Mainnet",
		Url:         "https://rpc-1.zyx.network/",
		ChainID:     55,
		ExplorerUrl: "https://zyxscan.com",
		Currency:    "ZYX",
	},
	{
		Name:        "High Performance Blockchain",
		Url:         "https://hpbnode.com",
		ChainID:     269,
		ExplorerUrl: "https://hscan.org",
		Currency:    "HPB",
	},
	{
		Name:        "GoChain",
		Url:         "https://rpc.gochain.io",
		ChainID:     60,
		ExplorerUrl: "https://explorer.gochain.io",
		Currency:    "GO",
	},
	{
		Name:        "Palm",
		Url:         "https://palm-mainnet.public.blastapi.io",
		ChainID:     11297108109,
		ExplorerUrl: "https://explorer.palm.io",
		Currency:    "PALM",
	},
	{
		Name:        "Expanse Network",
		Url:         "https://node.expanse.tech",
		ChainID:     2,
		ExplorerUrl: "",
		Currency:    "EXP",
	},
	{
		Name:        "Cube Chain Mainnet",
		Url:         "https://http-mainnet-sg.cube.network",
		ChainID:     1818,
		ExplorerUrl: "https://cubescan.network",
		Currency:    "",
	},
	{
		Name:        "Görli",
		Url:         "https://rpc.goerli.mudit.blog",
		ChainID:     5,
		ExplorerUrl: "https://goerli.etherscan.io/,https://stats.goerli.net/",
		Currency:    "GOR",
	},
	{
		Name:        "KardiaChain Mainnet",
		Url:         "https://rpc.kardiachain.io",
		ChainID:     24,
		ExplorerUrl: "https://explorer.kardiachain.io",
		Currency:    "",
	},
	{
		Name:        "ThaiChain",
		Url:         "https://rpc.dome.cloud",
		ChainID:     7,
		ExplorerUrl: "",
		Currency:    "TCH",
	},
	{
		Name:        "Metadium Mainnet",
		Url:         "https://api.metadium.com/prod",
		ChainID:     11,
		ExplorerUrl: "",
		Currency:    "META",
	},
	{
		Name:        "Flare Mainnet",
		Url:         "https://flare-api.flare.network/ext/C/rpc",
		ChainID:     14,
		ExplorerUrl: "https://flare-explorer.flare.network/",
		Currency:    "FLR",
	},
	{
		Name:        "Diode Prenet",
		Url:         "https://prenet.diode.io:8443/",
		ChainID:     15,
		ExplorerUrl: "",
		Currency:    "DIODE",
	},
	{
		Name:        "ThaiChain 2.0 ThaiFi",
		Url:         "https://rpc.thaifi.com",
		ChainID:     17,
		ExplorerUrl: "",
		Currency:    "TFI",
	},
	{
		Name:        "ELA-DID-Sidechain Mainnet",
		Url:         "",
		ChainID:     22,
		ExplorerUrl: "",
		Currency:    "ELA",
	},
	{
		Name:        "ShibaChain",
		Url:         "https://rpc.shibachain.net",
		ChainID:     27,
		ExplorerUrl: "https://exp.shibachain.net",
		Currency:    "SHIB",
	},
	{
		Name:        "Genesis L1",
		Url:         "https://rpc.genesisl1.org",
		ChainID:     29,
		ExplorerUrl: "https://explorer.genesisl1.org",
		Currency:    "L1",
	},
	{
		Name:        "GoodData Mainnet",
		Url:         "https://rpc.goodata.io",
		ChainID:     33,
		ExplorerUrl: "",
		Currency:    "GooD",
	},
	{
		Name:        "TBWG Chain",
		Url:         "https://rpc.tbwg.io",
		ChainID:     35,
		ExplorerUrl: "",
		Currency:    "TBG",
	},
	{
		Name:        "Valorbit",
		Url:         "https://rpc.valorbit.com/v2",
		ChainID:     38,
		ExplorerUrl: "",
		Currency:    "VAL",
	},
	{
		Name:        "Darwinia Crab Network",
		Url:         "http://crab-rpc.darwinia.network",
		ChainID:     44,
		ExplorerUrl: "https://crab.subscan.io",
		Currency:    "CRAB",
	},
	{
		Name:        "Core Chain MainNet",
		Url:         "https://rpc.coredao.org",
		ChainID:     1116,
		ExplorerUrl: "https://scan.coredao.org",
		Currency:    "Core",
	},
	{
		Name:        "XinFin Network Mainnet",
		Url:         "https://rpc.xinfin.network",
		ChainID:     50,
		ExplorerUrl: "",
		Currency:    "XDC",
	},
	{
		Name:        "Ontology Mainnet",
		Url:         "https://dappnode1.ont.io:20339",
		ChainID:     58,
		ExplorerUrl: "https://explorer.ont.io",
		Currency:    "ONG",
	},
	{
		Name:        "EOS Mainnet",
		Url:         "https://api.eosargentina.io",
		ChainID:     59,
		ExplorerUrl: "https://bloks.eosargentina.io",
		Currency:    "EOS",
	},
	{
		Name:        "Ethereum Classic Mainnet",
		Url:         "https://ethereumclassic.network",
		ChainID:     61,
		ExplorerUrl: "https://blockscout.com/etc/mainnet",
		Currency:    "ETC",
	},
	{
		Name:        "Ellaism",
		Url:         "https://jsonrpc.ellaism.org",
		ChainID:     64,
		ExplorerUrl: "",
		Currency:    "ELLA",
	},
	{
		Name:        "SoterOne Mainnet",
		Url:         "https://rpc.soter.one",
		ChainID:     68,
		ExplorerUrl: "",
		Currency:    "SOTER",
	},
	{
		Name:        "IDChain Mainnet",
		Url:         "https://idchain.one/rpc/",
		ChainID:     74,
		ExplorerUrl: "https://explorer.idchain.one",
		Currency:    "EIDI",
	},
	{
		Name:        "Mix",
		Url:         "https://rpc2.mix-blockchain.org:8647",
		ChainID:     76,
		ExplorerUrl: "",
		Currency:    "MIX",
	},
	{
		Name:        "POA Network Sokol",
		Url:         "https://sokol.poa.network",
		ChainID:     77,
		ExplorerUrl: "https://blockscout.com/poa/sokol",
		Currency:    "SPOA",
	},
	{
		Name:        "PrimusChain mainnet",
		Url:         "https://ethnode.primusmoney.com/mainnet",
		ChainID:     78,
		ExplorerUrl: "",
		Currency:    "PETH",
	},
	{
		Name:        "CMP Mainnet",
		Url:         "https://mainnet.block.caduceus.foundation",
		ChainID:     256256,
		ExplorerUrl: "https://mainnet.scan.caduceus.foundation/",
		Currency:    "",
	},
	{
		Name:        "GeneChain",
		Url:         "https://rpc.genechain.io",
		ChainID:     80,
		ExplorerUrl: "https://scan.genechain.io",
		Currency:    "RNA",
	},
	{
		Name:        "opBNB Mainnet",
		Url:         "https://opbnb-mainnet-rpc.bnbchain.org",
		ChainID:     204,
		ExplorerUrl: "https://opbnbscan.com/",
		Currency:    "BNB",
	},
	{
		Name:        "Arbitrum Nova",
		Url:         "https://nova.arbitrum.io/rpc",
		ChainID:     42170,
		ExplorerUrl: "https://nova-explorer.arbitrum.io",
		Currency:    "ETH",
	},
	{
		Name:        "ZKFair Mainnet",
		Url:         "https://rpc.zkfair.io",
		ChainID:     42766,
		ExplorerUrl: "https://scan.zkfair.io/",
		Currency:    "ZKF",
	},
	{
		Name:        "GateChain Mainnet",
		Url:         "https://evm.gatenode.cc",
		ChainID:     86,
		ExplorerUrl: "https://www.gatescan.org",
		Currency:    "GT",
	},
	{
		Name:        "Nova Network",
		Url:         "https://rpc.novanetwork.io:9070",
		ChainID:     87,
		ExplorerUrl: "https://explorer.novanetwork.io",
		Currency:    "SNT",
	},
	{
		Name:        "Garizon Stage0",
		Url:         "https://s0.garizon.net/rpc",
		ChainID:     90,
		ExplorerUrl: "https://explorer.garizon.com",
		Currency:    "GAR",
	},
	{
		Name:        "Garizon Stage1",
		Url:         "https://s1.garizon.net/rpc",
		ChainID:     91,
		ExplorerUrl: "https://explorer.garizon.com",
		Currency:    "GAR",
	},
	{
		Name:        "Garizon Stage2",
		Url:         "https://s2.garizon.net/rpc",
		ChainID:     92,
		ExplorerUrl: "https://explorer.garizon.com",
		Currency:    "GAR",
	},
	{
		Name:        "Garizon Stage3",
		Url:         "https://s3.garizon.net/rpc",
		ChainID:     93,
		ExplorerUrl: "https://explorer.garizon.com",
		Currency:    "GAR",
	},
	{
		Name:        "NEXT Smart Chain",
		Url:         "https://rpc.nextsmartchain.com",
		ChainID:     96,
		ExplorerUrl: "https://explorer.nextsmartchain.com",
		Currency:    "NEXT",
	},
	{
		Name:        "Taiko Katla L2",
		Url:         "https://taiko-katla.blockpi.network/v1/rpc/public",
		ChainID:     167008,
		ExplorerUrl: "https://explorer.katla.taiko.xyz/",
		Currency:    "ETH",
	},
	{
		Name:        "Scroll",
		Url:         "https://rpc.scroll.io",
		ChainID:     534352,
		ExplorerUrl: "https://scrollscan.com/",
		Currency:    "ETH",
	},
	{
		Name:        "POA Network Core",
		Url:         "https://core.poanetwork.dev",
		ChainID:     99,
		ExplorerUrl: "https://blockscout.com/poa/core",
		Currency:    "POA",
	},
	{
		Name:        "EtherInc",
		Url:         "https://api.einc.io/jsonrpc/mainnet",
		ChainID:     101,
		ExplorerUrl: "",
		Currency:    "ETI",
	},
	{
		Name:        "EtherLite Chain",
		Url:         "https://rpc.etherlite.org",
		ChainID:     111,
		ExplorerUrl: "",
		Currency:    "ETL",
	},
	{
		Name:        "Fuse Sparknet",
		Url:         "https://rpc.fusespark.io",
		ChainID:     123,
		ExplorerUrl: "",
		Currency:    "SPARK",
	},
	{
		Name:        "Decentralized Web Mainnet",
		Url:         "https://decentralized-web.tech/dw_rpc.php",
		ChainID:     124,
		ExplorerUrl: "",
		Currency:    "DWU",
	},
	{
		Name:        "OYchain Mainnet",
		Url:         "https://rpc.mainnet.oychain.io",
		ChainID:     126,
		ExplorerUrl: "https://explorer.oychain.io",
		Currency:    "OY",
	},
	{
		Name:        "Factory 127 Mainnet",
		Url:         "",
		ChainID:     127,
		ExplorerUrl: "",
		Currency:    "FETH",
	},
	{
		Name:        "DAX CHAIN",
		Url:         "https://rpc.prodax.io",
		ChainID:     142,
		ExplorerUrl: "",
		Currency:    "DAX",
	},
	{
		Name:        "Lightstreams Mainnet",
		Url:         "https://node.mainnet.lightstreams.io",
		ChainID:     163,
		ExplorerUrl: "",
		Currency:    "PHT",
	},
	{
		Name:        "Seele Mainnet",
		Url:         "https://rpc.seelen.pro/",
		ChainID:     186,
		ExplorerUrl: "https://seeleview.net",
		Currency:    "Seele",
	},
	{
		Name:        "BMC Mainnet",
		Url:         "https://mainnet.bmcchain.com/",
		ChainID:     188,
		ExplorerUrl: "https://bmc.blockmeta.com",
		Currency:    "BTM",
	},
	{
		Name:        "BitTorrent Chain Mainnet",
		Url:         "https://rpc.bittorrentchain.io/",
		ChainID:     199,
		ExplorerUrl: "https://scan.bittorrentchain.io",
		Currency:    "BTT",
	},
	{
		Name:        "Arbitrum on xDai",
		Url:         "https://arbitrum.xdaichain.com/",
		ChainID:     200,
		ExplorerUrl: "https://blockscout.com/xdai/arbitrum",
		Currency:    "xDAI",
	},
	{
		Name:        "Freight Trust Network",
		Url:         "http://13.57.207.168:3435",
		ChainID:     211,
		ExplorerUrl: "",
		Currency:    "0xF",
	},
	{
		Name:        "Permission",
		Url:         "https://blockchain-api-mainnet.permission.io/rpc",
		ChainID:     222,
		ExplorerUrl: "",
		Currency:    "ASK",
	},
	{
		Name:        "Setheum",
		Url:         "",
		ChainID:     258,
		ExplorerUrl: "",
		Currency:    "SETM",
	},
	{
		Name:        "SUR Blockchain Network",
		Url:         "https://sur.nilin.org",
		ChainID:     262,
		ExplorerUrl: "https://explorer.surnet.org",
		Currency:    "SRN",
	},
	{
		Name:        "Web3Q Mainnet",
		Url:         "https://mainnet.web3q.io:8545",
		ChainID:     333,
		ExplorerUrl: "https://explorer.mainnet.web3q.io",
		Currency:    "W3Q",
	},
	{
		Name:        "Lisinski",
		Url:         "https://rpc-bitfalls1.lisinski.online",
		ChainID:     385,
		ExplorerUrl: "",
		Currency:    "LISINSKI",
	},
	{
		Name:        "Rupaya",
		Url:         "",
		ChainID:     499,
		ExplorerUrl: "",
		Currency:    "RUPX",
	},
	{
		Name:        "Double-A Chain Mainnet",
		Url:         "https://rpc.acuteangle.com",
		ChainID:     512,
		ExplorerUrl: "https://scan.acuteangle.com",
		Currency:    "AAC",
	},
	{
		Name:        "Vela1 Chain Mainnet",
		Url:         "https://rpc.velaverse.io",
		ChainID:     555,
		ExplorerUrl: "https://exp.velaverse.io",
		Currency:    "CLASS",
	},
	{
		Name:        "ZetaChain Mainnet",
		Url:         "https://zetachain-evm.blockpi.network/v1/rpc/public",
		ChainID:     7000,
		ExplorerUrl: "https://explorer.zetachain.com/",
		Currency:    "ZETA",
	},
	{
		Name:        "Tao Network",
		Url:         "https://rpc.testnet.tao.network",
		ChainID:     558,
		ExplorerUrl: "",
		Currency:    "TAO",
	},
	{
		Name:        "Karura Network",
		Url:         "",
		ChainID:     686,
		ExplorerUrl: "",
		Currency:    "KAR",
	},
	{
		Name:        "BlockChain Station Mainnet",
		Url:         "https://rpc-mainnet.bcsdev.io",
		ChainID:     707,
		ExplorerUrl: "https://explorer.bcsdev.io",
		Currency:    "BCS",
	},
	{
		Name:        "cheapETH",
		Url:         "https://node.cheapeth.org/rpc",
		ChainID:     777,
		ExplorerUrl: "",
		Currency:    "cTH",
	},
	{
		Name:        "Acala Network",
		Url:         "",
		ChainID:     787,
		ExplorerUrl: "",
		Currency:    "ACA",
	},
	{
		Name:        "Haic",
		Url:         "https://orig.haichain.io/",
		ChainID:     803,
		ExplorerUrl: "",
		Currency:    "HAIC",
	},
	{
		Name:        "Ambros Chain Mainnet",
		Url:         "https://mainnet.ambroschain.com",
		ChainID:     880,
		ExplorerUrl: "https://explorer.ambroschain.com",
		Currency:    "AMBR",
	},
	{
		Name:        "Nepal Blockchain Network",
		Url:         "https://api.nepalblockchain.dev",
		ChainID:     977,
		ExplorerUrl: "",
		Currency:    "YETI",
	},
	{
		Name:        "Lucky Network",
		Url:         "https://rpc.luckynetwork.org",
		ChainID:     998,
		ExplorerUrl: "https://explorer.luckynetwork.org,https://lnscan.org",
		Currency:    "L99",
	},
	{
		Name:        "Evrice Network",
		Url:         "https://meta.evrice.com",
		ChainID:     1010,
		ExplorerUrl: "",
		Currency:    "EVC",
	},
	{
		Name:        "Newton",
		Url:         "https://global.rpc.mainnet.newtonproject.org",
		ChainID:     1012,
		ExplorerUrl: "",
		Currency:    "NEW",
	},
	{
		Name:        "Sakura",
		Url:         "",
		ChainID:     1022,
		ExplorerUrl: "",
		Currency:    "SKU",
	},
	{
		Name:        "Clover Mainnet",
		Url:         "https://rpc-ivy.clover.finance",
		ChainID:     1024,
		ExplorerUrl: "",
		Currency:    "CLV",
	},
	{
		Name:        "Conflux eSpace",
		Url:         "https://evm.confluxrpc.com",
		ChainID:     1030,
		ExplorerUrl: "https://evm.confluxscan.net",
		Currency:    "CFX",
	},
	{
		Name:        "MathChain",
		Url:         "https://mathchain-asia.maiziqianbao.net/rpc",
		ChainID:     1139,
		ExplorerUrl: "",
		Currency:    "MATH",
	},
	{
		Name:        "Iora Chain",
		Url:         "https://dataseed.iorachain.com",
		ChainID:     1197,
		ExplorerUrl: "https://explorer.iorachain.com",
		Currency:    "IORA",
	},
	{
		Name:        "World Trade Technical Chain Mainnet",
		Url:         "https://rpc.cadaut.com",
		ChainID:     1202,
		ExplorerUrl: "https://explorer.cadaut.com",
		Currency:    "WTT",
	},
	{
		Name:        "Popcateum Mainnet",
		Url:         "https://dataseed.popcateum.org",
		ChainID:     1213,
		ExplorerUrl: "https://explorer.popcateum.org",
		Currency:    "POP",
	},
	{
		Name:        "EnterChain Mainnet",
		Url:         "https://tapi.entercoin.net/",
		ChainID:     1214,
		ExplorerUrl: "https://explorer.entercoin.net",
		Currency:    "ENTER",
	},
	{
		Name:        "HALO Mainnet",
		Url:         "https://nodes.halo.land",
		ChainID:     1280,
		ExplorerUrl: "https://browser.halo.land",
		Currency:    "HO",
	},
	{
		Name:        "Moonbase Alpha",
		Url:         "https://rpc.api.moonbase.moonbeam.network",
		ChainID:     1287,
		ExplorerUrl: "https://moonbase.moonscan.io",
		Currency:    "DEV",
	},
	{
		Name:        "Moonrock",
		Url:         "https://rpc.api.moonrock.moonbeam.network",
		ChainID:     1288,
		ExplorerUrl: "",
		Currency:    "ROC",
	},
	{
		Name:        "Catecoin Chain Mainnet",
		Url:         "https://send.catechain.com",
		ChainID:     1618,
		ExplorerUrl: "",
		Currency:    "CATE",
	},
	{
		Name:        "Atheios",
		Url:         "https://wallet.atheios.com:8797",
		ChainID:     1620,
		ExplorerUrl: "",
		Currency:    "ATH",
	},
	{
		Name:        "Btachain",
		Url:         "https://dataseed1.btachain.com/",
		ChainID:     1657,
		ExplorerUrl: "",
		Currency:    "BTA",
	},
	{
		Name:        "Teslafunds",
		Url:         "https://tsfapi.europool.me",
		ChainID:     1856,
		ExplorerUrl: "",
		Currency:    "TSF",
	},
	{
		Name:        "EtherGem",
		Url:         "https://jsonrpc.egem.io/custom",
		ChainID:     1987,
		ExplorerUrl: "",
		Currency:    "EGEM",
	},
	{
		Name:        "Edgeware Mainnet",
		Url:         "https://mainnet1.edgewa.re",
		ChainID:     2021,
		ExplorerUrl: "",
		Currency:    "EDG",
	},
	{
		Name:        "Rangers Protocol Mainnet",
		Url:         "https://mainnet.rangersprotocol.com/api/jsonrpc",
		ChainID:     2025,
		ExplorerUrl: "https://scan.rangersprotocol.com",
		Currency:    "RPG",
	},
	{
		Name:        "Ecoball Mainnet",
		Url:         "https://api.ecoball.org/ecoball/",
		ChainID:     2100,
		ExplorerUrl: "https://scan.ecoball.org",
		Currency:    "ECO",
	},
	{
		Name:        "Evanesco Mainnet",
		Url:         "https://seed4.evanesco.org:8546",
		ChainID:     2213,
		ExplorerUrl: "https://explorer.evanesco.org",
		Currency:    "EVA",
	},
	{
		Name:        "Kortho Mainnet",
		Url:         "https://www.kortho-chain.com",
		ChainID:     2559,
		ExplorerUrl: "",
		Currency:    "KTO",
	},
	{
		Name:        "Manta Pacific Mainnet",
		Url:         "https://pacific-rpc.manta.network/http",
		ChainID:     169,
		ExplorerUrl: "https://pacific-explorer.manta.network/",
		Currency:    "MANTA",
	},
	{
		Name:        "Bittex Mainnet",
		Url:         "https://rpc1.bittexscan.info",
		ChainID:     3690,
		ExplorerUrl: "https://bittexscan.com",
		Currency:    "BTX",
	},
	{
		Name:        "EraSwap Mainnet",
		Url:         "https://mainnet.eraswap.network",
		ChainID:     5197,
		ExplorerUrl: "",
		Currency:    "ES",
	},
	{
		Name:        "Uzmi Network Mainnet",
		Url:         "https://network.uzmigames.com.br/",
		ChainID:     5315,
		ExplorerUrl: "",
		Currency:    "UZMI",
	},
	{
		Name:        "Wegochain Rubidium Mainnet",
		Url:         "https://proxy.wegochain.io",
		ChainID:     5869,
		ExplorerUrl: "https://scan2.wegochain.io",
		Currency:    "RBD",
	},
	{
		Name:        "Pixie Chain Mainnet",
		Url:         "https://http-mainnet.chain.pixie.xyz",
		ChainID:     6626,
		ExplorerUrl: "https://scan.chain.pixie.xyz",
		Currency:    "PIX",
	},
	{
		Name:        "Shyft Mainnet",
		Url:         "https://rpc.shyft.network/",
		ChainID:     7341,
		ExplorerUrl: "https://bx.shyft.network",
		Currency:    "SHYFT",
	},
	{
		Name:        "Teleport",
		Url:         "https://evm-rpc.teleport.network",
		ChainID:     8000,
		ExplorerUrl: "https://evm-explorer.teleport.network,https://explorer.teleport.network",
		Currency:    "TELE",
	},
	{
		Name:        "Linea",
		Url:         "https://linea.blockpi.network/v1/rpc/public",
		ChainID:     59144,
		ExplorerUrl: "https://lineascan.build/",
		Currency:    "ETH",
	},
	{
		Name:        "Electroneum Mainnet",
		Url:         "https://rpc.electroneum.com",
		ChainID:     52014,
		ExplorerUrl: "https://blockexplorer.electroneum.com/",
		Currency:    "ETN",
	},
	{
		Name:        "TOOL Global Mainnet",
		Url:         "https://mainnet-web3.wolot.io",
		ChainID:     8723,
		ExplorerUrl: "https://www.olo.network",
		Currency:    "OLO",
	},
	{
		Name:        "Mantle",
		Url:         "https://mantle-mainnet.public.blastapi.io",
		ChainID:     5000,
		ExplorerUrl: "https://explorer.mantle.xyz/",
		Currency:    "MNT",
	},
	{
		Name:        "bloxberg",
		Url:         "https://core.bloxberg.org",
		ChainID:     8995,
		ExplorerUrl: "",
		Currency:    "U+25B3",
	},
	{
		Name:        "Evmos",
		Url:         "https://eth.bd.evmos.org:8545",
		ChainID:     9001,
		ExplorerUrl: "https://evm.evmos.org,https://www.mintscan.io/evmos",
		Currency:    "EVMOS",
	},
	{
		Name:        "Genesis Coin",
		Url:         "https://genesis-gn.com",
		ChainID:     9100,
		ExplorerUrl: "",
		Currency:    "GNC",
	},
	{
		Name:        "Blockchain Genesis Mainnet",
		Url:         "https://eu.mainnet.xixoio.com",
		ChainID:     10101,
		ExplorerUrl: "",
		Currency:    "GEN",
	},
	{
		Name:        "WAGMI",
		Url:         "https://api.trywagmi.xyz/rpc",
		ChainID:     11111,
		ExplorerUrl: "https://trywagmi.xyz",
		Currency:    "WGM",
	},
	{
		Name:        "Singularity ZERO Mainnet",
		Url:         "https://zerorpc.singularity.gold",
		ChainID:     12052,
		ExplorerUrl: "https://zeroscan.singularity.gold",
		Currency:    "ZERO",
	},
	{
		Name:        "Phoenix Mainnet",
		Url:         "https://rpc.phoenixplorer.com/",
		ChainID:     13381,
		ExplorerUrl: "https://phoenixplorer.com",
		Currency:    "PHX",
	},
	{
		Name:        "MetaDot Mainnet",
		Url:         "https://mainnet.metadot.network",
		ChainID:     16000,
		ExplorerUrl: "",
		Currency:    "MTT",
	},
	{
		Name:        "BTCIX Network",
		Url:         "https://seed.btcix.org/rpc",
		ChainID:     19845,
		ExplorerUrl: "https://btcixscan.com",
		Currency:    "BTCIX",
	},
	{
		Name:        "omChain Mainnet",
		Url:         "https://seed.omlira.com",
		ChainID:     21816,
		ExplorerUrl: "https://explorer.omlira.com",
		Currency:    "OML",
	},
	{
		Name:        "Webchain",
		Url:         "https://node1.webchain.network",
		ChainID:     24484,
		ExplorerUrl: "",
		Currency:    "WEB",
	},
	{
		Name:        "MintMe.com Coin",
		Url:         "https://node1.mintme.com",
		ChainID:     24734,
		ExplorerUrl: "",
		Currency:    "MINTME",
	},
	{
		Name:        "Ethersocial Network",
		Url:         "https://api.esn.gonspool.com",
		ChainID:     31102,
		ExplorerUrl: "",
		Currency:    "ESN",
	},
	{
		Name:        "Energi Mainnet",
		Url:         "https://nodeapi.energi.network",
		ChainID:     39797,
		ExplorerUrl: "",
		Currency:    "NRG",
	},
	{
		Name:        "pegglecoin",
		Url:         "",
		ChainID:     42069,
		ExplorerUrl: "",
		Currency:    "peggle",
	},
	{
		Name:        "Athereum",
		Url:         "https://ava.network:21015/ext/evm/rpc",
		ChainID:     43110,
		ExplorerUrl: "",
		Currency:    "ATH",
	},
	{
		Name:        "Canto MainNet",
		Url:         "https://canto.slingshot.finance",
		ChainID:     7700,
		ExplorerUrl: "https://evm.explorer.canto.io",
		Currency:    "CANTO",
	},
	{
		Name:        "Canto TestNet",
		Url:         "https://eth.plexnode.wtf",
		ChainID:     740,
		ExplorerUrl: "http://testnet-explorer.canto.neobase.one",
		Currency:    "CANTO",
	},
	{
		Name:        "Lisk  Mainnet",
		Url:         "https://rpc.api.lisk.com",
		ChainID:     1135,
		ExplorerUrl: "https://blockscout.lisk.com",
		Currency:    "LSK",
	},
	{
		Name:        "REI Network",
		Url:         "https://rpc.rei.network",
		ChainID:     47805,
		ExplorerUrl: "https://scan.rei.network",
		Currency:    "REI",
	},
	{
		Name:        "REI Chain Mainnet",
		Url:         "https://rei-rpc.moonrhythm.io",
		ChainID:     55555,
		ExplorerUrl: "https://reiscan.com",
		Currency:    "REI",
	},
	{
		Name:        "eCredits Mainnet",
		Url:         "https://rpc.ecredits.com",
		ChainID:     63000,
		ExplorerUrl: "https://explorer.ecredits.com",
		Currency:    "ECS",
	},
	{
		Name:        "Thinkium Mainnet Chain 0",
		Url:         "https://proxy.thinkiumrpc.net/",
		ChainID:     70000,
		ExplorerUrl: "https://chain0.thinkiumscan.net",
		Currency:    "TKM",
	},
	{
		Name:        "Thinkium Mainnet Chain 1",
		Url:         "https://proxy1.thinkiumrpc.net/",
		ChainID:     70001,
		ExplorerUrl: "https://chain1.thinkiumscan.net",
		Currency:    "TKM",
	},
	{
		Name:        "Thinkium Mainnet Chain 2",
		Url:         "https://proxy2.thinkiumrpc.net/",
		ChainID:     70002,
		ExplorerUrl: "https://chain2.thinkiumscan.net",
		Currency:    "TKM",
	},
	{
		Name:        "Thinkium Mainnet Chain 103",
		Url:         "https://proxy103.thinkiumrpc.net/",
		ChainID:     70103,
		ExplorerUrl: "https://chain103.thinkiumscan.net",
		Currency:    "TKM",
	},
	{
		Name:        "Mumbai",
		Url:         "https://matic-mumbai.chainstacklabs.com",
		ChainID:     80001,
		ExplorerUrl: "https://mumbai.polygonscan.com",
		Currency:    "MATIC",
	},
	{
		Name:        "UB Smart Chain",
		Url:         "https://rpc.uschain.network",
		ChainID:     99999,
		ExplorerUrl: "",
		Currency:    "UBC",
	},
	{
		Name:        "QuarkChain Mainnet Root",
		Url:         "http://jrpc.mainnet.quarkchain.io:38391/",
		ChainID:     100000,
		ExplorerUrl: "",
		Currency:    "QKC",
	},
	{
		Name:        "QuarkChain Mainnet Shard 0",
		Url:         "https://mainnet-s0-ethapi.quarkchain.io",
		ChainID:     100001,
		ExplorerUrl: "https://mainnet.quarkchain.io/0",
		Currency:    "QKC",
	},
	{
		Name:        "QuarkChain Mainnet Shard 1",
		Url:         "https://mainnet-s1-ethapi.quarkchain.io",
		ChainID:     100002,
		ExplorerUrl: "https://mainnet.quarkchain.io/1",
		Currency:    "QKC",
	},
	{
		Name:        "QuarkChain Mainnet Shard 2",
		Url:         "https://mainnet-s2-ethapi.quarkchain.io",
		ChainID:     100003,
		ExplorerUrl: "https://mainnet.quarkchain.io/2",
		Currency:    "QKC",
	},
	{
		Name:        "QuarkChain Mainnet Shard 3",
		Url:         "https://mainnet-s3-ethapi.quarkchain.io",
		ChainID:     100004,
		ExplorerUrl: "https://mainnet.quarkchain.io/3",
		Currency:    "QKC",
	},
	{
		Name:        "QuarkChain Mainnet Shard 4",
		Url:         "https://mainnet-s4-ethapi.quarkchain.io",
		ChainID:     100005,
		ExplorerUrl: "https://mainnet.quarkchain.io/4",
		Currency:    "QKC",
	},
	{
		Name:        "QuarkChain Mainnet Shard 5",
		Url:         "https://mainnet-s5-ethapi.quarkchain.io",
		ChainID:     100006,
		ExplorerUrl: "https://mainnet.quarkchain.io/5",
		Currency:    "QKC",
	},
	{
		Name:        "QuarkChain Mainnet Shard 6",
		Url:         "https://mainnet-s6-ethapi.quarkchain.io",
		ChainID:     100007,
		ExplorerUrl: "https://mainnet.quarkchain.io/6",
		Currency:    "QKC",
	},
	{
		Name:        "QuarkChain Mainnet Shard 7",
		Url:         "https://mainnet-s7-ethapi.quarkchain.io",
		ChainID:     100008,
		ExplorerUrl: "https://mainnet.quarkchain.io/7",
		Currency:    "QKC",
	},
	{
		Name:        "BROChain Mainnet",
		Url:         "https://rpc.brochain.org",
		ChainID:     108801,
		ExplorerUrl: "https://explorer.brochain.org",
		Currency:    "BRO",
	},
	{
		Name:        "QuarkChain Devnet Root",
		Url:         "http://jrpc.devnet.quarkchain.io:38391/",
		ChainID:     110000,
		ExplorerUrl: "",
		Currency:    "QKC",
	},
	{
		Name:        "QuarkChain Devnet Shard 0",
		Url:         "https://devnet-s0-ethapi.quarkchain.io",
		ChainID:     110001,
		ExplorerUrl: "https://devnet.quarkchain.io/0",
		Currency:    "QKC",
	},
	{
		Name:        "QuarkChain Devnet Shard 1",
		Url:         "https://devnet-s1-ethapi.quarkchain.io",
		ChainID:     110002,
		ExplorerUrl: "https://devnet.quarkchain.io/1",
		Currency:    "QKC",
	},
	{
		Name:        "QuarkChain Devnet Shard 2",
		Url:         "https://devnet-s2-ethapi.quarkchain.io",
		ChainID:     110003,
		ExplorerUrl: "https://devnet.quarkchain.io/2",
		Currency:    "QKC",
	},
	{
		Name:        "QuarkChain Devnet Shard 3",
		Url:         "https://devnet-s3-ethapi.quarkchain.io",
		ChainID:     110004,
		ExplorerUrl: "https://devnet.quarkchain.io/3",
		Currency:    "QKC",
	},
	{
		Name:        "QuarkChain Devnet Shard 4",
		Url:         "https://devnet-s4-ethapi.quarkchain.io",
		ChainID:     110005,
		ExplorerUrl: "https://devnet.quarkchain.io/4",
		Currency:    "QKC",
	},
	{
		Name:        "QuarkChain Devnet Shard 5",
		Url:         "https://devnet-s5-ethapi.quarkchain.io",
		ChainID:     110006,
		ExplorerUrl: "https://devnet.quarkchain.io/5",
		Currency:    "QKC",
	},
	{
		Name:        "QuarkChain Devnet Shard 6",
		Url:         "https://devnet-s6-ethapi.quarkchain.io",
		ChainID:     110007,
		ExplorerUrl: "https://devnet.quarkchain.io/6",
		Currency:    "QKC",
	},
	{
		Name:        "QuarkChain Devnet Shard 7",
		Url:         "https://devnet-s7-ethapi.quarkchain.io",
		ChainID:     110008,
		ExplorerUrl: "https://devnet.quarkchain.io/7",
		Currency:    "QKC",
	},
	{
		Name:        "Akroma",
		Url:         "https://remote.akroma.io",
		ChainID:     200625,
		ExplorerUrl: "",
		Currency:    "AKA",
	},
	{
		Name:        "Alaya Mainnet",
		Url:         "https://openapi.alaya.network/rpc",
		ChainID:     201018,
		ExplorerUrl: "https://scan.alaya.network",
		Currency:    "atp",
	},
	{
		Name:        "PlatON Mainnet",
		Url:         "https://openapi.platon.network/rpc",
		ChainID:     210425,
		ExplorerUrl: "https://scan.platon.network",
		Currency:    "lat",
	},
	{
		Name:        "ARTIS sigma1",
		Url:         "https://rpc.sigma1.artis.network",
		ChainID:     246529,
		ExplorerUrl: "",
		Currency:    "ATS",
	},
	{
		Name:        "Social Smart Chain Mainnet",
		Url:         "https://socialsmartchain.digitalnext.business",
		ChainID:     281121,
		ExplorerUrl: "",
		Currency:    "$OC",
	},
	{
		Name:        "Shardeum Liberty 1.3",
		Url:         "https://liberty10.shardeum.org/",
		ChainID:     8080,
		ExplorerUrl: "https://explorer.liberty10.shardeum.org/",
		Currency:    "SHM",
	},
	{
		Name:        "Shardeum Liberty 2.0",
		Url:         "https://liberty20.shardeum.org/",
		ChainID:     8080,
		ExplorerUrl: "https://explorer.liberty20.shardeum.org/",
		Currency:    "SHM",
	},
	{
		Name:        "Vision - Mainnet",
		Url:         "https://infragrid.v.network/ethereum/compatible",
		ChainID:     888888,
		ExplorerUrl: "https://www.visionscan.org",
		Currency:    "VS",
	},
	{
		Name:        "Eluvio Content Fabric",
		Url:         "https://host-76-74-28-226.contentfabric.io/eth/",
		ChainID:     955305,
		ExplorerUrl: "https://explorer.eluv.io",
		Currency:    "ELV",
	},
	{
		Name:        "Etho Protocol",
		Url:         "https://rpc.ethoprotocol.com",
		ChainID:     1313114,
		ExplorerUrl: "https://explorer.ethoprotocol.com",
		Currency:    "ETHO",
	},
	{
		Name:        "Xerom",
		Url:         "https://rpc.xerom.org",
		ChainID:     1313500,
		ExplorerUrl: "",
		Currency:    "XERO",
	},
	{
		Name:        "Kintsugi",
		Url:         "https://rpc.kintsugi.themerge.dev",
		ChainID:     1337702,
		ExplorerUrl: "https://explorer.kintsugi.themerge.dev",
		Currency:    "kiETH",
	},
	{
		Name:        "Musicoin",
		Url:         "https://mewapi.musicoin.tw",
		ChainID:     7762959,
		ExplorerUrl: "",
		Currency:    "MUSIC",
	},
	{
		Name:        "PepChain Churchill",
		Url:         "https://churchill-rpc.pepchain.io",
		ChainID:     13371337,
		ExplorerUrl: "",
		Currency:    "TPEP",
	},
	{
		Name:        "IOLite",
		Url:         "https://net.iolite.io",
		ChainID:     18289463,
		ExplorerUrl: "",
		Currency:    "ILT",
	},
	{
		Name:        "quarkblockchain",
		Url:         "https://hz.rpc.qkiscan.cn",
		ChainID:     20181205,
		ExplorerUrl: "",
		Currency:    "QKI",
	},
	{
		Name:        "Auxilium Network Mainnet",
		Url:         "https://rpc.auxilium.global",
		ChainID:     28945486,
		ExplorerUrl: "",
		Currency:    "AUX",
	},
	{
		Name:        "Joys Digital Mainnet",
		Url:         "https://node.joys.digital",
		ChainID:     35855456,
		ExplorerUrl: "",
		Currency:    "JOYS",
	},
	{
		Name:        "Aquachain",
		Url:         "https://c.onical.org",
		ChainID:     61717561,
		ExplorerUrl: "",
		Currency:    "AQUA",
	},
	{
		Name:        "Gather Mainnet Network",
		Url:         "https://mainnet.gather.network",
		ChainID:     192837465,
		ExplorerUrl: "https://explorer.gather.network",
		Currency:    "GTH",
	},
	{
		Name:        "Neon EVM DevNet",
		Url:         "https://proxy.devnet.neonlabs.org/solana",
		ChainID:     245022926,
		ExplorerUrl: "",
		Currency:    "NEON",
	},
	{
		Name:        "Neon EVM MainNet",
		Url:         "https://proxy.mainnet.neonlabs.org/solana",
		ChainID:     245022934,
		ExplorerUrl: "",
		Currency:    "NEON",
	},
	{
		Name:        "OneLedger Mainnet",
		Url:         "https://mainnet-rpc.oneledger.network",
		ChainID:     311752642,
		ExplorerUrl: "https://mainnet-explorer.oneledger.network",
		Currency:    "OLT",
	},
	{
		Name:        "Gather Tesnet Network",
		Url:         "https://testnet.gather.network",
		ChainID:     356256156,
		ExplorerUrl: "https://testnet-explorer.gather.network",
		Currency:    "GTH",
	},
	{
		Name:        "Gather Devnet Network",
		Url:         "https://devnet.gather.network",
		ChainID:     486217935,
		ExplorerUrl: "https://devnet-explorer.gather.network",
		Currency:    "GTH",
	},
	{
		Name:        "IPOS Network",
		Url:         "https://rpc.iposlab.com",
		ChainID:     1122334455,
		ExplorerUrl: "",
		Currency:    "IPOS",
	},
	{
		Name:        "Aurora Betanet",
		Url:         "https://betanet.aurora.dev/",
		ChainID:     1313161556,
		ExplorerUrl: "",
		Currency:    "ETH",
	},
	{
		Name:        "Harmony Mainnet Shard 1",
		Url:         "https://s1.api.harmony.one",
		ChainID:     1666600001,
		ExplorerUrl: "",
		Currency:    "ONE",
	},
	{
		Name:        "Harmony Mainnet Shard 2",
		Url:         "https://s2.api.harmony.one",
		ChainID:     1666600002,
		ExplorerUrl: "",
		Currency:    "ONE",
	},
	{
		Name:        "Harmony Mainnet Shard 3",
		Url:         "https://s3.api.harmony.one",
		ChainID:     1666600003,
		ExplorerUrl: "",
		Currency:    "ONE",
	},
	{
		Name:        "DataHopper",
		Url:         "https://23.92.21.121:8545",
		ChainID:     2021121117,
		ExplorerUrl: "",
		Currency:    "HOP",
	},
	{
		Name:        "Pirl",
		Url:         "https://wallrpc.pirl.io",
		ChainID:     3125659152,
		ExplorerUrl: "",
		Currency:    "PIRL",
	},
	{
		Name:        "Ntity Mainnet",
		Url:         "https://rpc.ntity.io",
		ChainID:     197710212030,
		ExplorerUrl: "https://blockscout.ntity.io",
		Currency:    "NTT",
	},
	{
		Name:        "Molereum Network",
		Url:         "https://molereum.jdubedition.com",
		ChainID:     6022140761023,
		ExplorerUrl: "",
		Currency:    "MOLE",
	},
	{
		Name:        "Qitmeer Network Mainnet",
		Url:         "https://evm-dataseed1.meerscan.io",
		ChainID:     813,
		ExplorerUrl: "https://qng.qitmeer.io/",
		Currency:    "MEER",
	},
	{
		Name:        "TechPay Photon Mainnet",
		Url:         "https://api.techpay.io/",
		ChainID:     2569,
		ExplorerUrl: "https://tpcscan.com/",
		Currency:    "TPC",
	},
}
